// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgilywzoguqgookorvrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnaWx5d3pvZ3VxZ29va29ydnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTQ5NjUsImV4cCI6MjA2NDU5MDk2NX0.t3wxDrBw4MY0ouZUAf4e3EHWH1oqFSgz3NAP7uweS6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);